# Generated by Django 3.1.3 on 2021-02-02 01:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapaTematico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mapa', models.VarCharField(max_length=30, unique=True)),
                ('observacao', models.VarCharField(blank=True, max_length=200, null=True)),
                ('tipo_geometria', models.VarCharField(choices=[('PL', 'Polígono'), ('PT', 'Ponto'), ('LH', 'Linha'), (None, None)], max_length=10)),
                ('cor_linha', models.VarCharField(default=None, max_length=10)),
                ('tipo_linha', models.IntegerField(default=0)),
                ('tamanho_linha', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('cor_fundo', models.VarCharField(default=None, max_length=10)),
                ('textura_fundo', models.VarCharField(default=None, max_length=40)),
                ('cor_ponto', models.VarCharField(default=None, max_length=10)),
                ('tipo_ponto', models.VarCharField(choices=[('M', 'Marcador'), ('C', 'Círculo'), (None, None)], default=None, max_length=10)),
                ('tamanho_ponto', models.IntegerField(default=0)),
                ('valido', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=False)),
                ('deletado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amb_mapa_tematico',
            },
        ),
        migrations.CreateModel(
            name='VersaoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_revisao', models.VarCharField(max_length=30)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('observacao', models.VarCharField(max_length=200)),
                ('valido', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=False)),
                ('deletado', models.BooleanField(default=False)),
                ('processado', models.BooleanField(default=False)),
                ('mapa_tematico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiental.mapatematico')),
            ],
            options={
                'db_table': 'amb_versao_tema',
                'unique_together': {('mapa_tematico', 'nome_revisao', 'data_cadastro')},
            },
        ),
        migrations.CreateModel(
            name='VersaoTemaGeometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('versao_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiental.versaotema')),
            ],
            options={
                'db_table': 'amb_versao_tema_geom',
                'unique_together': {('versao_tema', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atributo', models.VarCharField(max_length=50)),
                ('tipo_dado', models.VarCharField(max_length=10)),
                ('origem', models.VarCharField(max_length=50)),
                ('versao_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiental.versaotema')),
            ],
            options={
                'db_table': 'amb_atributo',
                'unique_together': {('versao_tema', 'nome_atributo', 'tipo_dado')},
            },
        ),
        migrations.CreateModel(
            name='VersaoTemaAtributoGeometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.VarCharField(default=None, max_length=200, null=True)),
                ('numero', models.DecimalField(decimal_places=6, default=None, max_digits=15, null=True)),
                ('data', models.DateField(default=None, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiental.atributo')),
                ('versao_tema_geom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiental.versaotemageometria')),
            ],
            options={
                'db_table': 'amb_versao_tema_atr_geom',
                'unique_together': {('versao_tema_geom', 'atributo')},
            },
        ),
    ]
