# Generated by Django 3.1.3 on 2021-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atributo',
            name='visualizacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapatematico',
            name='opacidade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2, null=True),
        ),
    ]
