# Generated by Django 3.1.3 on 2021-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0002_auto_20210202_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapatematico',
            name='opacidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=2, null=True),
        ),
    ]
