# Generated by Django 3.1.3 on 2021-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0005_auto_20210202_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='deletado',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
