# Generated by Django 3.1.3 on 2021-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0006_auto_20210202_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
