# Generated by Django 3.1.3 on 2021-02-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiental', '0007_auto_20210202_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapatematico',
            name='nome_mapa',
            field=models.VarCharField(max_length=50, unique=True),
        ),
    ]
