AMB_INSERT_ATRIBUTO = """
INSERT INTO AMB_ATRIBUTO(NOME_ATRIBUTO, TIPO_DADO, ORIGEM, VERSAO_TEMA_ID)
VALUES('%s', '%s', '%s', %s)
"""

AMB_INSERT_GEOM = """
INSERT INTO AMB_VERSAO_TEMA_GEOM(ITEM, GEOM, VERSAO_TEMA_ID)
SELECT ID, GEOM, %s FROM %s
"""

AMB_PROCESSO = """
BEGIN 
    ETL_AMBIENTAL.CARREGA_TEMA_ATR_GEOM('%s'); 
END;
"""

SELECT_AMB_GEOMETRIA = """
SELECT TIPO_GEOMETRIA 
FROM AMB_MAPA_TEMATICO A
JOIN AMB_VERSAO_TEMA B ON(A.ID = B.MAPA_TEMATICO_ID)
WHERE B.ID = %s
"""

SELECT_AMB_POLIGONO = """
SELECT  COR_LINHA 
    ,   TIPO_LINHA
    ,   TAMANHO_LINHA
    ,   COR_FUNDO
    ,   TEXTURA_FUNDO
    ,   OPACIDADE
FROM AMB_MAPA_TEMATICO A
JOIN AMB_VERSAO_TEMA B ON(A.ID = B.MAPA_TEMATICO_ID)
WHERE B.ID = %s
"""

SELECT_AMB_LINHA = """
SELECT  COR_LINHA
    ,   TIPO_LINHA
    ,   TAMANHO_LINHA
FROM AMB_MAPA_TEMATICO A
JOIN AMB_VERSAO_TEMA B ON(A.ID = B.MAPA_TEMATICO_ID)
WHERE B.ID = %s
"""

SELECT_AMB_PONTO = """
SELECT  TIPO_PONTO
    ,   COR_PONTO
    ,   TAMANHO_PONTO
FROM AMB_MAPA_TEMATICO A
JOIN AMB_VERSAO_TEMA B ON(A.ID = B.MAPA_TEMATICO_ID)
WHERE B.ID = %s
"""
