ATRIBUTO_INDEX = """
    SELECT  JSON_OBJECT(
            A.ID
        ,   A.DESCRICAO
        ,   A.APELIDO
        ,   A.UNIDADE_MEDIDA
        ,   B.NOME_CALCULO
        ,   C.NOME_CATEGORIA
        ,   A.OBSERVACAO) JSON   
    FROM ATRIBUTO_CADASTRO A
    JOIN ATRIBUTO_CALCULO B ON(A.CALCULO_ID = B.ID)
    JOIN ATRIBUTO_CATEGORIA C ON(A.CATEGORIA_ID = C.ID)
    WHERE (A.ATIVO = 0
        OR A.VALIDO = 0)
"""

SELECT_ATRIBUTO = """
    SELECT DESCRICAO 
    FROM ATRIBUTO_CADASTRO
    WHERE TO_CHAR(OBSERVACAO) = TO_CHAR('LOTE')
"""


