INSERT_INTERPOLACAO = """
INSERT INTO INTERPOLACAO_GEOM(INTERPOLACAO_ID, VALOR, GEOM) VALUES(%s, %s, JSON_VALUE('%s', '$' RETURNING SDO_GEOMETRY))
"""

INTERPOLACAO_INDEX = """
    WITH
        SEL AS
            (
                SELECT  A.ID
                    ,   A.DESCRICAO
                    ,   B.DESCRICAO ATRIBUTO
                    ,   TO_CHAR(A.DATA , 'YYYY-MM-DD') DATA
                    ,   C.DESCRICAO TIPO_INTERPOLACAO
                    ,   A.LANCAMENTO_PIXEL
                    ,   A.VALIDO
                    ,   A.ATIVO
                FROM INTERPOLACAO_CADASTRO A
                JOIN ATRIBUTO_CADASTRO B ON(A.ATRIBUTO_ID = B.ID)
                JOIN INTERPOLACAO_TIPO C ON(A.TIPO_INTERPOLACAO_ID = C.ID)
                WHERE (A.VALIDO = 0
                    OR A.ATIVO = 0)
                AND A.DELETADO = 0
            )
    SELECT JSON_OBJECT(*) JSON FROM SEL
"""

INTERPOLACAO_LOTE = """
    SELECT DISTINCT ATRIBUTO DESCRICAO_ATRIBUTO
    FROM INTERPOLACAO_LOTE_PONTOS
    WHERE INTERPOLACAO_LOTE_ID = %s
    ORDER BY ATRIBUTO
"""

SELECT_INTERPOLACAO = """
SELECT ID FROM INTERPOLACAO_CADASTRO
WHERE DESCRICAO = 'LOTE - '|| %s ||'/'|| %s
"""

CADASTRO_AUTOMATICO = """
INSERT INTO INTERPOLACAO_CADASTRO (TIPO_INTERPOLACAO_ID, ATRIBUTO_ID, DESCRICAO, DATA, OBSERVACAO, ATIVO, VALIDO, LOTE, LOTE_ID, LANCAMENTO_PIXEL, PROCESSADO)
VALUES(%s, %s, 'LOTE - '|| %s ||'/'|| %s, TO_DATE('%s', 'DD/MM/YYYY'), 'LOTE GERADO POR TAREFA', 1, 0 , 1, %s, 1, 0)
"""

ABRANGENCIA_AUTOMATICO = """
INSERT INTO INTERPOLACAO_ABRANGENCIA(TALHAO_ID, INTERPOLACAO_ID)
VALUES(%s, %s)
"""

INSERT_INTER_LOTE = """
INSERT INTO INTERPOLACAO_GEOM(INTERPOLACAO_ID, VALOR, GEOM)
SELECT %s, "valor", GEOM FROM %s
"""

VIEW_INTERPOLACAO = """
SELECT  A.ID                            INTERPOLACAO_ID
        ,   A.DESCRICAO                     NOME_INTERPOLACAO
        ,   TO_CHAR(A.DATA, 'DD/MM/YYYY')   DATA
        ,   D.NOME_TALHAO
        ,   E.ID                            ATRIBUTO_ID
        ,   E.DESCRICAO                     NOME_ATRIBUTO
        ,   C.VALOR     
        ,   G.VALOR_INICIAL
        ,   G.VALOR_FINAL
        ,   G.HEXADECIMAL
        ,   G.COMPLEMENTO                   LEGENDA
        ,   SDO_UTIL.TO_WKTGEOMETRY(C.GEOM) GEOM
    FROM INTERPOLACAO_CADASTRO A
    JOIN INTERPOLACAO_ABRANGENCIA B ON(A.ID = B.INTERPOLACAO_ID)
    JOIN INTERPOLACAO_GEOM C ON(A.ID = C.INTERPOLACAO_ID)
    JOIN TALHAO_CADASTRO D ON (B.TALHAO_ID = D.ID)
    JOIN ATRIBUTO_CADASTRO E ON(A.ATRIBUTO_ID = E.ID)
    LEFT JOIN ATRIBUTO_COR F ON(E.ID = F.ATRIBUTO_ID)
    LEFT JOIN PALETA_COR G ON(F.PALETA_ID = G.PALETA_ID AND C.VALOR BETWEEN G.VALOR_INICIAL AND G.VALOR_FINAL)
    WHERE A.ID = %s
    
"""
